version: '3.5'

services:

  registry:
    container_name: ${REGISTRY_CONTAINER}
    image: registry:${TAG}
    hostname: ${NGINX_HOSTNAME}
    environment:
      VIRTUAL_HOST: ${REGISTRY_HOSTNAME}
      LETSENCRYPT_HOST: ${REGISTRY_HOSTNAME}
      LETSENCRYPT_EMAIL: ${REGISTRY_CONTAINER}@no-reply.com
    volumes:
      - ./registry:/var/lib/registry
    restart: always

networks:
  default:
    external:
      name: ${NGINX_PROXY_NET}
